// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO3l05I1eAsS33_bQdUHEo3YlCE0W3TV4',
    appId: '1:369951446481:web:25d0b0591aa93e74bdfcf0',
    messagingSenderId: '369951446481',
    projectId: 'gambitchess',
    authDomain: 'gambitchess.firebaseapp.com',
    storageBucket: 'gambitchess.appspot.com',
    measurementId: 'G-BWXMGNGMDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqqW2W7cTqhydQlqC_bR9FemmlJrV7tc8',
    appId: '1:369951446481:android:ff90ec41c35aa1babdfcf0',
    messagingSenderId: '369951446481',
    projectId: 'gambitchess',
    storageBucket: 'gambitchess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqINQbrnFtSOSoOqRsq7E1fE94IWlsDU4',
    appId: '1:369951446481:ios:735822db7cce5e42bdfcf0',
    messagingSenderId: '369951446481',
    projectId: 'gambitchess',
    storageBucket: 'gambitchess.appspot.com',
    iosBundleId: 'com.example.gambit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqINQbrnFtSOSoOqRsq7E1fE94IWlsDU4',
    appId: '1:369951446481:ios:7869424c7bbbb881bdfcf0',
    messagingSenderId: '369951446481',
    projectId: 'gambitchess',
    storageBucket: 'gambitchess.appspot.com',
    iosBundleId: 'com.example.gambit.RunnerTests',
  );
}
